title: The Karnani-Axelrod Home

resources:
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js

views:
  - title: Example
    id: example
    cards:
      - title: test
        id: test
        type: markdown
        content: hi
