binary_sensor.linear_gd00z4_garage_door_opener_remote_controller_sensor_2:
  ignored: true
  polling_intensity: 0
sensor.linear_gd00z4_garage_door_opener_remote_controller_access_control:
  ignored: true
  polling_intensity: 0
sensor.linear_gd00z4_garage_door_opener_remote_controller_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.linear_gd00z4_garage_door_opener_remote_controller_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.linear_gd00z4_garage_door_opener_remote_controller_burglar:
  ignored: true
  polling_intensity: 0
sensor.linear_gd00z4_garage_door_opener_remote_controller_sourcenodeid:
  ignored: true
  polling_intensity: 0
light.family_room_lights_level:
  refresh_value: true
light.master_bedroom_lights_level:
  refresh_value: true
