- platform: template
  sensors:
    kitchen_door_template:
      friendly_name: Kitchen Door
      value_template: '{% if is_state("sensor.kitchen_door_access_control", "23") %}Closed{% else %}Open{% endif %}'
