- alias: Someones Home
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: 'home'
    - service: climate.set_preset_mode
      data:
        entity_id: climate.floor
        preset_mode: 'Run Schedule'
