- alias: Someones Home
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: none
        entity_id: climate.upstairs
    - service: climate.set_preset_mode
      data:
        entity_id: climate.floor
        preset_mode: 'Run Schedule'
