- alias: Low Battery Notification
  trigger:
    platform: template
    value_template: >
      {% for zwave in states.zwave if zwave.attributes.battery_level %}
        {%- if zwave.attributes.battery_level | int < 30 -%}
          {{true}}
        {%- endif -%}
      {%- endfor -%}
  action:
    service: persistent_notification.create 
    data_template:
      title: "Zwave device has low battery"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} needs new batteries.
