- alias: Turn on Coffee Maker
  trigger:
    - platform: time
      at: input_datetime.coffee_machine
  condition:
    condition: state
    entity_id: binary_sensor.everyone_not_home
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: switch.coffee_machine

- alias: Turn off Coffee Machine
  trigger:
    - platform: state
      entity_id: switch.coffee_machine
      to: 'on'
      for:
        hours: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_machine

