- alias: Turn on Coffee Maker
  trigger:
    - platform: time
      at: input_datetime.coffee_machine
  condition:
    - condition: state
      entity_id: binary_sensor.everyone_not_home
      state: 'off'
    - condition: state
      entity_id: switch.coffee_machine
      state: 'off'
      for:
        hours: 3
  action:
    service: homeassistant.turn_on
    entity_id: switch.coffee_machine

- alias: Turn off Coffee Machine
  trigger:
    - platform: state
      entity_id: switch.coffee_machine
      to: 'on'
      for:
        hours: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_machine

- alias: Reset Coffee Machine Meter
  trigger:
    - platform: time
      at: '00:00:01'
  condition:
    - condition: template
      value_template: "{{ now().day == 1 }}"
  action:
    - service: zwave_js.reset_meter
      entity_id: sensor.coffee_machine_energy
