- alias: Turn on Coffee Maker
  trigger:
    - platform: state
      entity_id:  binary_sensor.coffee_machine_on
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.coffee_machine

- alias: Turn off Coffee Machine
  trigger:
    - platform: state
      entity_id: switch.coffee_machine
      to: 'on'
      for:
        hours: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_machine

