- alias: Turn on Coffee Maker
  trigger:
    - platform: time
      at: input_datetime.coffee_machine
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: state
      entity_id: switch.coffee_machine
      state: 'off'
      for:
        hours: 3
  action:
    service: homeassistant.turn_on
    entity_id: switch.coffee_machine

- alias: Turn off Coffee Machine
  trigger:
    - platform: state
      entity_id: switch.coffee_machine
      to: 'on'
      for:
        hours: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.coffee_machine

