- alias: Sync Entry Lights
  trigger:
    platform: state
    entity_id: switch.stairs_light_switch, switch.entry_way_lights_switch
  action:
    service_template: >
      {% if trigger.to_state.state == "on" %}
      homeassistant.turn_on
      {% else %}
      homeassistant.turn_off
      {% endif %}
    data_template:
      entity_id: >
        {% if trigger.from_state.entity_id == "switch.entry_way_lights_switch" %}
        switch.stairs_light_switch
        {% elif trigger.from_state.entity_id == "switch.stairs_light_switch" %}
        switch.entry_way_lights_switch
        {% endif %}

