- alias: 'Family Room Full brightness'
  trigger:
    - event_type: zwave.scene_activated
      platform: event
      event_data:
        entity_id: zwave.family_room_lights
        scene_id: 1
        scene_data: 3
  action:
    service: homeassistant.turn_on
    entity_id: light.family_room_lights_level
    data:
      brightness: 255
