- alias: 'Family Room Full brightness'
  trigger:
    - event_type: zwave.scene_activated
      platform: event
      event_data:
        entity_id: zwave.family_room_lights
        scene_id: 1
        scene_data: 3
  action:
    service: homeassistant.turn_on
    entity_id: light.family_room_lights_level
    data:
      brightness: 255

- alias: 'Turn on the Christmas Tree'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: state
    entity_id: binary_sensor.everyone_not_home
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.christmas_tree

      
