- alias: Turn on Garage Lights
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: sun
        before: sunrise
  action:
    service: switch.turn_on
    entity_id: switch.garage_lights_switch

- alias: Turn off Garage Lights
  trigger:
    - platform: state
      entity_id: switch.garage_lights_switch
      to: 'on'
      for:
        minutes: 1
    - platform: state
      entity_id: switch.garage_lights_switch
      to: 'on'
      for:
        minutes: 5
    - platform: state
      entity_id: switch.garage_lights_switch
      to: 'on'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.kitchen_door_template
        state: 'Closed'
      - condition: state
        entity_id: cover.garage_door
        state: 'closed'
  action:
    service: switch.turn_off
    entity_id: switch.garage_lights_switch
