- alias: Turn on Garage Lights
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: sun
        before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: switch.garage_lights_switch

- alias: Into Garage from Kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_door_template
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: sun
        before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: switch.garage_lights_switch

- alias: Turn off Garage Lights
  trigger:
    - platform: state
      entity_id: switch.garage_lights_switch
      to: 'on'
      for:
        minutes: 1
    - platform: state
      entity_id: switch.garage_lights_switch
      to: 'on'
      for:
        minutes: 5
    - platform: state
      entity_id: switch.garage_lights_switch
      to: 'on'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_door_template
        state: 'off'
      - condition: state
        entity_id: cover.garage_door
        state: 'closed'
  action:
    service: homeassistant.turn_off
    entity_id: switch.garage_lights_switch

- alias: Notify Open Garage Door
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'on'
    for:
      minutes: 15
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'not_home'
  action:
    service: notify.slack
    data_template:
      message: "Garage door is open and no one is home"
