- alias: Everyone's Gone
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
    for:
      minutes: 30
  action:
    - service: lock.lock
      entity_id: group.all_locks
    - service: cover.close_cover
      entity_id: group.all_covers
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - group.all_switches
    - service: nest.set_away_mode
      data:
        away_mode: 'away'
