- alias: Everyone's Gone
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
    for:
      minutes: 30
  action:
    - service: lock.lock
      entity_id: lock.front_door_lock_locked
    - service: cover.close_cover
      entity_id: group.all_covers
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - group.switches_off_on_gone
    - if:
        condition: state
        entity_id: input_boolean.keep_coffee_on_next_away
        state: 'off'
      then:
        - service: homeassistant.turn_off
          entity_id: switch.coffee_machine
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
        entity_id: climate.upstairs
    - service: climate.set_temperature
      entity_id: climate.floor
      data:
        temperature: '{{state_attr("climate.floor", "min_temp")}}'
        hvac_mode: heat
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.keep_coffee_on_next_away
