- alias: Everyone's Gone
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
    for:
      minutes: 30
  action:
    - service: lock.lock
      entity_id: lock.front_door_lock_locked
    - service: cover.close_cover
      entity_id: group.all_covers
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - group.all_switches
    - service: climate.set_preset_mode
      data:
        preset_mode: eco
        entity_id: climate.upstairs
    - service: climate.set_temperature
      entity_id: climate.floor
      data:
        temperature: '{{state_attr("climate.floor", "min_temp")}}'
        hvac_mode: heat
