- alias: Into Kitchen
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_door
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_motion_sensor
        state: 'off'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: switch.kitchen_lights_switch
