- alias: Kitchen Light On
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      to:
         'on'
  condition:
    condition: numeric_state
    entity_id: sensor.kitchen_motion_luminance
    below: '70'
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_lights_switch

- alias: Lock Door
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_door_sensor
    to: 'off'
    for:
      seconds: 30
  action:
    service: lock.lock
    entity_id: lock.kitchen_door_lock_locked

- alias: Pantry Light On Motion
  trigger:
    platform: state
    entity_id: binary_sensor.pantry_motion_sensor
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.pantry_lights_switch

- alias: Pantry Light Off Motion
  trigger:
    platform: state
    entity_id: binary_sensor.pantry_motion_sensor
    to: 'off'
    for:
      seconds: 20
  action:
    service: switch.turn_off
    entity_id: switch.pantry_lights_switch
