- alias: 'Master Bedroom Full brightness'
  trigger:
    - event_type: zwave.scene_activated
      platform: event
      event_data:
        entity_id: zwave.master_bedroom_lights
        scene_id: 1
        scene_data: 3
  action:
    service: homeassistant.turn_on
    entity_id: light.master_bedroom_lights_level
    data:
      brightness: 255

- alias: 'Goodnight'
  trigger:
    - event_type: zwave.scene_activated
      platform: event
      event_data:
        entity_id: zwave.master_bedroom_lights
        scene_id: 2
        scene_data: 3
  action:
      - service: script.turn_on
        entity_id: script.goodnight
