- alias: 'Master Bedroom Full brightness'
  trigger:
    - event_type: zwave_js_value_notification
      platform: event
      event_data:
        node_id: 21
        property_key: "001"
        value: "KeyPressed2x"
  action:
    service: homeassistant.turn_on
    entity_id: light.master_bedroom_lights_level
    data:
      brightness: 255

- alias: 'Goodnight'
  trigger:
    - event_type: zwave_js_value_notification
      platform: event
      event_data:
        node_id: 21
        property_key: "002"
        value: "KeyPressed2x"
  action:
      - service: script.turn_on
        entity_id: script.goodnight
