- alias: Outdoor Lights
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
  action:
      service: homeassistant.turn_on
      entity_id:
        - group.outdoor_lights

- alias: Turn off Outdoor Lights
  trigger:
    - platform: time
      at: "00:00"
  action:
    service: homeassistant.turn_off
    entity_id: 
      - group.outdoor_lights

