- alias: Garden Lights
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:45:00"
  action:
      service: switch.turn_on
      entity_id: switch.garden_lights_switch

- alias: Turn off Garden Lights
  trigger:
    - platform: state
      entity_id: switch.garden_lights_switch
      to: 'on'
      for:
        hours: 3
  action:
    service: switch.turn_off
    entity_id: switch.garden_lights_switch

