- alias: Garden Lights
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
  action:
      service: homeassistant.turn_on
      entity_id:
        - switch.garden_lights_switch
        - switch.porch_lights_switch

- alias: Turn off Garden Lights
  trigger:
    - platform: time
      at: "00:00"
  action:
    service: homeassistant.turn_off
    entity_id: 
      - switch.garden_lights_switch
      - switch.porch_lights_switch


