- alias: Garden Lights
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:45:00"
  action:
      service: switch.turn_on
      entity_id: switch.switch_2

- alias: Turn off Garden Lights
  trigger:
    - platform: state
      entity_id: switch.switch_2
      state: 'on'
      for:
        hours: 5
  action:
    service: switch.turn_off
    entity_id: switch.switch_2

